### ISSUE TITLE
a newbie to crawler

### ISSUE THREAD

**Issue by Kingsleychoo** [MatthewSteeples/TweetCrawler#1]
when i run you main window on vb 2015 why it have the remote server returned an error:(401) unauthorized

**Comment by MatthewSteeples** [comment]
Hi @Kingsleychoo, I'm afraid that this hasn't been updated since Twitter disabled their old authentication method so until it gets support for OAuth it won't work. It's not something I have time to do at the moment.

**Comment by Kingsleychoo** [comment]
ok thank you very much
